<%if isTTO then%>
	<table border="0" width="100%">
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">Copyright © 2000-2004 The
	      Ticket Office</font></td>
	  </tr>
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">All Rights Reserved</font></td>
	  </tr>
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">Contact the </font><a href="mailto:webmaster@the-ticket-office.com"><font face="Verdana" size="1">webmaster</font></a></td>
	  </tr>
	</table>
<%else%>
	<table border="0" width="100%">
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">
	    EZ-Show-Tickets.com</font></td>
	  </tr>
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">All Rights Reserved</font></td>
	  </tr>
	  <tr>
	    <td width="100%"><font face="Verdana" size="1">Contact the </font><a href="mailto:hgoodman@cgc-intl.com"><font face="Verdana" size="1">webmaster</font></a></td>
	  </tr>
	</table>


<%end if%>